### ISSUE TITLE
Verification for signup form

### ISSUE THREAD

**Issue by Jwcode-uk** [CardCollab/cardcollab-core#29]

**Comment by Jwcode-uk** [comment]
**added**
- added email validation
- added username check against blacklist
- added DOB validation
**ToDo**
- extend blacklist to cover profanity
- validate username doesn't already exist
- check first name and last against profanity blastlist

**Comment by oliverbutler** [comment]
In regards to whether a username exists, same with email, due to cognito's limitations this isnt possible to do on the front end. We could...

- Write a method on the BE that uses the aws-sdk's listUser() function to check if a user exists with that email/username. 
- Pursue our own auth further

**Comment by Jwcode-uk** [comment]
**Added**
- serverside verfication added using Joi
- approprate error messages added

**Comment by Jwcode-uk** [comment]
as we have reached the scunthorpe problem I am closing this issue for now
