### ISSUE TITLE
Storing uploaded images

### ISSUE THREAD

**Issue by oliverbutler** [CardCollab/cardcollab-core#4]
As the app is Serverless the images need to be stored in a static directory.

Possibly

**Client**  -- upload Image --> **Lambda@Edge** -- AWS API --> **S3 Bucket**
            ^-------- returns URL ------------|

- We can't store them 'locally' as locally doesn't exist for Serverless

**Comment by Jwcode-uk** [comment]
working on compression for upload

**Comment by Jwcode-uk** [comment]
basic compression complete working on upload to s3p currently

**Comment by Jwcode-uk** [comment]
need to discuss setting up AWS S3 bucket access
