### ISSUE TITLE
Possible security vulnerability.

### ISSUE THREAD

**Issue by oliverbutler** [CardCollab/cardcollab-core#47]
Its late, but I thought of a possible JWT expiry vulnerability. This wouldn't normally be an issue, but with serverless deployment around the globe it very well may be.

Because expiry time is based on the time of whatever lambda@edge endpoint signs the token, you, through the use of a VPN to access a different lambda endpoint, say 10+ hours in the future, where the token is still valid and irrevokable.

Possible fix

- Use IAT & EXP together so it will only be not valid before the IAT.
This has its own issues, it would allow any JWT to be used within its 10 minute slot, more than once by 'moving' across timezones.
- Ensure all JWTs are signed at GMT +0 
 This would mean that the tokens may appear out of date, but SHOULD remove this vulnerability

**Comment by Jwcode-uk** [comment]
Time should be standardised to UTC not based on local system time as this would leave to major issues across a range of parts of the program.

I think all back end time should be standardised to UTC and then we could add a simple conversion to the users timezone if this is ever required.

**Comment by Jwcode-uk** [comment]
Time should be standardised to UTC not based on local system time as this would leave to major issues across a range of parts of the program.

I think all back end time should be standardised to UTC and then we could add a simple conversion to the users timezone if this is ever required.

**Comment by oliverbutler** [comment]
Looking at it, I think we can use new Date().toISOString() to get the UTC time, everywhere. including the DB. then we take that string and useDate(theDate).toLocaleString() on the FE to convert everything to the users timezone

**Comment by oliverbutler** [comment]
Fixed
